baseURL = "https://singh-snehil.github.io"
title = "Health Claims Exchange"
description = "Open-source, widely agreed protocol for Health Claims Exchange"

enableRobotsTXT = true
enableGitInfo = true

# language settings
contentDir = "content/en"
defaultContentLanguage = "en"
# tell Hugo not to include the /en/ element in the URL path for English docs
defaultContentLanguageInSubdir = false
# useful when translating
enableMissingTranslationPlaceholders = true
# disable taxonomies
disableKinds = ["taxonomy", "taxonomyTerm"]

###############################################################################
# Hugo - Top-level navigation (horizontal)
###############################################################################
[menu]
  [[menu.main]]
    name = "Governance"
    weight = -101
    pre = "<i class='fas fa-landmark pr-2'></i>"
    url = "/governance/"
  [[menu.main]]
    name = "Community"
    weight = -100
    pre = "<i class='fas fa-users pr-2'></i>"
    url = "/community"
  [[menu.main]]
    name = "FAQs"
    weight = -99
    pre = "<i class='fas fa-question-circle pr-2'></i>"
    url = "/faq"

###############################################################################
# Docsy - Goldmark markdown parser
###############################################################################
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "tango"
    guessSyntax = "true"

# Docsy - Image processing configuration
###############################################################################
[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  anchor = "smart"

###############################################################################
# Docsy - Services configuration
###############################################################################
[services]
  [services.googleAnalytics]
  id = "UA-135379910-1"

###############################################################################
# Docsy - Language configuration
###############################################################################
[languages]
  [languages.en]
    title = "Health Claims Exchange"
    description = "Open-source, widely agreed protocol for Health Claims Exchange"
    languageName ="English"
    # weight used for sorting in the language menu
    weight = 1

###############################################################################
# Docsy - Site Parameters
###############################################################################
[params]
  github_repo = "https://github.com/website"
  github_project_repo = "https://github.com/"

  #RSSLink = ""
  author = "snehil" # add your company name
  github = "swasth" # add your github profile name
  twitter = "hcx" # add your twitter profile

  copyright = "The HCX Authors."
  privacy_policy = "https://policies.google.com/privacy"

  # Google Custom Search Engine ID.
  #gcs_engine_id = ""

  # Text label for the version menu in the top bar of the website.
  #version_menu = "HCX Version"

  # The major.minor version tag for the version of the docs represented in this
  # branch of the repository. Used in the "version-banner" partial to display a
  # version number for this doc set.
  version = "master"

  # Flag used in the "version-banner" partial to decide whether to display a
  # banner on every page indicating that this is an archived version of the docs.
  archived_version = false

  # A link to latest version of the docs. Used in the "version-banner" partial to
  # point people to the main doc site.
  url_latest_version = ""

  # A variable used in various docs to determine URLs for config files etc.
  # To find occurrences, search the repo for 'params "githubbranch"'.
  githubbranch = "master"

  # These entries appear in the drop-down menu at the top of the website.
  #[[params.versions]] 

  # User interface configuration
  [params.ui]
    # Enable the logo
    navbar_logo = true
    # Enable to show the side bar menu in its compact state.
    sidebar_menu_compact = true
    # Enable the search box in the side bar.
    sidebar_search_disable = true
    # Set to true to disable breadcrumb navigation.
    breadcrumb_disable = false
    # Show expand/collapse icon for sidebar sections
    sidebar_menu_foldable = true
    # Disable about button in footer
    footer_about_disable = true

      # Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
      # This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
      # If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
      # add "hide_feedback: true" to the page's front matter.
      [params.ui.feedback]
        enable = true
        # The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
        yes = 'Glad to hear it! Please <a href="https://github.com/">tell us how we can improve</a>.'
        no = 'Sorry to hear that. Please <a href="https://github.com/">tell us how we can improve</a>.'

  # Links in footer
  [params.links]
    [[params.links.user]]
      name = "Twitter"
      url = "https://twitter.com/"
      icon = "fab fa-twitter"
      desc = "Follow us on Twitter to get the latest news!"
    [[params.links.user]]
      name = "Mailing list"
      url = "/docs/about/community/#mailing-list"
      icon = "fa fa-envelope"
      desc = "Join the HCX Mailing List!"
    [[params.links.user]]
      name = "Weekly Community Call"
      url = "/docs/about/community/#weekly-community-call"
      icon = "fa fa-calendar"
      desc = "Join the weekly HCX Community Call!"

[module]
  proxy = "direct"
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.73.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false